services:
  - type: web
    name: backend-bancas
    env: node
    plan: starter
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bancas-db
          property: connectionString
